var car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car === 'subaru'? I predict True.");
console.log(car === 'subaru');
var num = 1;
console.log("Is num == 1? I predict True.");
console.log(num == 1);
console.log("Is num === 1? I predict True.");
console.log(num === 1);
console.log("Is num != 0? I predict True.");
console.log(num != 2);
console.log("Is num !== 0? I predict True.");
console.log(num !== 2);
console.log("Is num != 1? I predict False.");
console.log(num != 1);
console.log("Is num !== 1? I predict False.");
console.log(num !== 1);
console.log("Is num != 0? I predict False.");
console.log(num == 2);
console.log("Is num !== 0? I predict False.");
console.log(num === 2);
var bool = false;
console.log("Is bool === false? I predict True.");
console.log(bool === false);
